### ISSUE TITLE
How can i select the subtitle as a String 

### ISSUE THREAD

**Issue by EwigLife** [MuhmdHsn313/IQPlayer#4]
Hi, 
I am trying to build a video Language learning app. In which user can bring his fav movie and play it with subtitles and from subtitles he/she (the User) can select a single word or a pharase. which will then be translated. can you guide me how can i use IQPlayer to resolve this issue. as i am trying and i cannot select the words from subtitles, 

Thanks.

**Comment by MuhmdHsn313** [comment]
Unfortunately, at this time you cannot do this with IQPlayer. We will support that in the future, God willing.
